name: Happy Commit
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  check:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/happy-commit.yml@main
